
import type { Program } from './types';
import {
  Plane,
  Cog,
  Landmark,
  Bot,
  Code,
  ShieldCheck,
  Atom,
  Beaker,
  Dna,
  TestTube,
  Globe,
  Sigma,
  HeartPulse,
  Briefcase,
  TrendingUp,
  LineChart,
  ShoppingCart,
  Ship,
  Hotel,
  Scale,
  Building2,
  Brush,
  Mic,
  BookOpen,
  GraduationCap,
  Dumbbell,
  Leaf,
  Factory,
  Soup,
  LucideIcon,
  Book,
  Anchor,
  Cpu,
  TrendingDown,
} from 'lucide-react';

export const courseCategories: Record<string, string[]> = {
  "STEM & Engineering": [
    "Aerospace / Aeronautical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical / Electronic Engineering",
    "Mechatronics / Robotics",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Petroleum / Energy Engineering",
    "Environmental Engineering",
  ],
  "Computer Science & Data": [
    "Computer Science / Software Engineering",
    "Data Science / Artificial Intelligence",
    "Cybersecurity / Network Management",
    "Cyber Physical Systems / IoT",
  ],
  "Math & Natural Sciences": [
    "Mathematics / Applied Mathematics",
    "Physics",
    "Chemistry",
    "Biology / Life Sciences",
    "Geography / Geosciences",
    "Statistics",
  ],
  "Health & Medical": [
    "Medicine (MD / integrated programmes)",
    "Dentistry / Dental Medicine",
    "Pharmacy",
    "Nursing (BSc / MSc)",
    "Public Health",
    "Biomedical Science / Laboratory Science",
    "Physiotherapy / Occupational Therapy",
    "Medical Biotechnology",
  ],
  "Business, Economics & Social Sciences": [
    "Business Administration / Management",
    "Economics",
    "Finance / Banking / Accounting",
    "Marketing / Digital Marketing",
    "International Relations / Political Science",
    "Psychology",
    "Sociology / Social Work",
    "Human Resources",
  ],
  "Arts, Design & Humanities": [
    "Architecture",
    "Design / Industrial Design",
    "Fine Arts / Visual Arts",
    "Media & Communications",
    "Languages & Literature / Translation",
    "African Studies / Area Studies",
  ],
  "Professional & Emerging Fields": [
    "Law (LLB / LLM)",
    "Education / Teaching",
    "Supply Chain / Logistics",
    "Hospitality & Tourism Management",
    "Sports Science / Performance",
    "Renewable Energy / Sustainable Tech",
    "Urban Planning / Smart Cities",
    "Agricultural Sciences / Food Tech",
    "Culinary Arts / Chef Programs",
    "Aviation / Pilot Training",
  ],
};


export const programData: Program[] = [
  // STEM & Engineering BSc
  {
    courseId: 'aero_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Aerospace / Aeronautical Engineering',
    tuitionRangeEUR: { min: 2000, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Common in technical universities. Some specialized MSc programs may have higher fees.',
    estTotalCost: { easternEurope: { min: 8000, max: 13500 }, westernEurope: { min: 18000, max: 30000 } },
  },
  {
    courseId: 'mech_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Mechanical Engineering',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Widely available with strong practical components.',
    estTotalCost: { easternEurope: { min: 7500, max: 13000 }, westernEurope: { min: 17000, max: 28000 } },
  },
  {
    courseId: 'civil_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Civil Engineering',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Focus on infrastructure and urban development, strong in Poland and Hungary.',
    estTotalCost: { easternEurope: { min: 7500, max: 13000 }, westernEurope: { min: 17000, max: 28000 } },
  },
  {
    courseId: 'elec_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Electrical / Electronic Engineering',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Curriculum often includes power systems, electronics, and telecommunications.',
    estTotalCost: { easternEurope: { min: 7500, max: 13500 }, westernEurope: { min: 17500, max: 29000 } },
  },
  {
    courseId: 'mecha_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Mechatronics / Robotics',
    tuitionRangeEUR: { min: 2500, max: 8000 },
    typicalLanguage: 'English',
    notes: 'Integrates mechanics, electronics, and computer science.',
    estTotalCost: { easternEurope: { min: 8500, max: 14000 }, westernEurope: { min: 19000, max: 30000 } },
  },
  {
    courseId: 'chem_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Chemical Engineering',
    tuitionRangeEUR: { min: 2000, max: 8000 },
    typicalLanguage: 'English',
    notes: 'Process engineering and material science are key components.',
    estTotalCost: { easternEurope: { min: 8000, max: 14000 }, westernEurope: { min: 18000, max: 29000 } },
  },
  {
    courseId: 'biomed_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Biomedical Engineering',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Combines engineering principles with medical sciences.',
    estTotalCost: { easternEurope: { min: 9000, max: 15000 }, westernEurope: { min: 20000, max: 32000 } },
  },
  {
    courseId: 'energy_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Petroleum / Energy Engineering',
    tuitionRangeEUR: { min: 3000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Specialized programs can be pricier. Strong in Norway, but tuition may be higher.',
    estTotalCost: { easternEurope: { min: 9500, max: 16000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  {
    courseId: 'env_eng_bsc',
    degreeLevel: 'BSc',
    subject: 'Environmental Engineering',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Focus on sustainability and resource management. Growing demand.',
    estTotalCost: { easternEurope: { min: 8000, max: 13500 }, westernEurope: { min: 18000, max: 29000 } },
  },
  // Computer Science & Data BSc
  {
    courseId: 'cs_se_bsc',
    degreeLevel: 'BSc',
    subject: 'Computer Science / Software Engineering',
    tuitionRangeEUR: { min: 2000, max: 8000 },
    typicalLanguage: 'English',
    notes: 'Extremely popular and widely available in English across Europe.',
    estTotalCost: { easternEurope: { min: 7500, max: 14000 }, westernEurope: { min: 19000, max: 28000 } },
  },
  {
    courseId: 'ds_ai_bsc',
    degreeLevel: 'BSc',
    subject: 'Data Science / Artificial Intelligence',
    tuitionRangeEUR: { min: 3000, max: 9000 },
    typicalLanguage: 'English',
    notes: 'High-demand field with many new programs emerging.',
    estTotalCost: { easternEurope: { min: 9000, max: 15000 }, westernEurope: { min: 20000, max: 32000 } },
  },
  {
    courseId: 'cyber_sec_bsc',
    degreeLevel: 'BSc',
    subject: 'Cybersecurity / Network Management',
    tuitionRangeEUR: { min: 2500, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Practical, hands-on programs are common in technical universities.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 30000 } },
  },
  // Math & Natural Sciences BSc
  {
    courseId: 'math_bsc',
    degreeLevel: 'BSc',
    subject: 'Mathematics / Applied Mathematics',
    tuitionRangeEUR: { min: 1500, max: 6500 },
    typicalLanguage: 'English',
    notes: 'Foundational degree, very affordable in many public universities.',
    estTotalCost: { easternEurope: { min: 7000, max: 12000 }, westernEurope: { min: 16000, max: 25000 } },
  },
  {
    courseId: 'physics_bsc',
    degreeLevel: 'BSc',
    subject: 'Physics',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Theoretical and experimental physics programs available.',
    estTotalCost: { easternEurope: { min: 7500, max: 13000 }, westernEurope: { min: 18000, max: 28000 } },
  },
  {
    courseId: 'chemistry_bsc',
    degreeLevel: 'BSc',
    subject: 'Chemistry',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Lab fees may apply. Check for specialized tracks like biochemistry.',
    estTotalCost: { easternEurope: { min: 7500, max: 13000 }, westernEurope: { min: 18000, max: 28000 } },
  },
  {
    courseId: 'biology_bsc',
    degreeLevel: 'BSc',
    subject: 'Biology / Life Sciences',
    tuitionRangeEUR: { min: 2000, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Includes molecular biology, genetics, and ecology.',
    estTotalCost: { easternEurope: { min: 7500, max: 13500 }, westernEurope: { min: 18000, max: 29000 } },
  },
  {
    courseId: 'geography_bsc',
    degreeLevel: 'BSc',
    subject: 'Geography / Geosciences',
    tuitionRangeEUR: { min: 1800, max: 7000 },
    typicalLanguage: 'English',
    notes: 'Human and physical geography tracks are common.',
    estTotalCost: { easternEurope: { min: 7200, max: 12500 }, westernEurope: { min: 17000, max: 27000 } },
  },
  {
    courseId: 'stats_bsc',
    degreeLevel: 'BSc',
    subject: 'Statistics',
    tuitionRangeEUR: { min: 2000, max: 7000 },
    typicalLanguage: 'English',
    notes: 'Often linked with data science or economics departments.',
    estTotalCost: { easternEurope: { min: 7500, max: 13000 }, westernEurope: { min: 18000, max: 28000 } },
  },
  // Health & Medical BSc
  {
    courseId: 'medicine_md_bsc',
    degreeLevel: 'BSc', 
    subject: 'Medicine (MD / integrated programmes)',
    tuitionRangeEUR: { min: 8000, max: 15000 },
    typicalLanguage: 'English + Local',
    notes: 'Clinical years require local language. High tuition but cheaper than US.',
    estTotalCost: { easternEurope: { min: 17000, max: 26000 }, westernEurope: { min: 28000, max: 40000 } },
  },
  {
    courseId: 'dentistry_bsc',
    degreeLevel: 'BSc',
    subject: 'Dentistry / Dental Medicine',
    tuitionRangeEUR: { min: 6000, max: 15000 },
    typicalLanguage: 'English + Local',
    notes: 'Like medicine, clinical work necessitates local language skills.',
    estTotalCost: { easternEurope: { min: 15000, max: 25000 }, westernEurope: { min: 26000, max: 40000 } },
  },
  {
    courseId: 'nursing_bsc',
    degreeLevel: 'BSc',
    subject: 'Nursing (BSc / MSc)',
    tuitionRangeEUR: { min: 2000, max: 9500 },
    typicalLanguage: 'English + Local',
    notes: 'Heavy emphasis on placements in local healthcare systems.',
    estTotalCost: { easternEurope: { min: 8000, max: 15000 }, westernEurope: { min: 19000, max: 30000 } },
  },
  {
    courseId: 'biomed_sci_bsc',
    degreeLevel: 'BSc',
    subject: 'Biomedical Science / Laboratory Science',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Research-focused, a pathway to medicine or PhDs.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19000, max: 31000 } },
  },
  {
    courseId: 'physio_bsc',
    degreeLevel: 'BSc',
    subject: 'Physiotherapy / Occupational Therapy',
    tuitionRangeEUR: { min: 3000, max: 12000 },
    typicalLanguage: 'English + Local',
    notes: 'Patient-facing roles require local language for clinical practice.',
    estTotalCost: { easternEurope: { min: 9500, max: 18000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  // Business, Economics & Social Sciences BSc
  {
    courseId: 'business_bsc',
    degreeLevel: 'BSc',
    subject: 'Business Administration / Management',
    tuitionRangeEUR: { min: 1500, max: 8000 },
    typicalLanguage: 'English',
    notes: 'Very affordable and widely available, especially in the Baltics and Poland.',
    estTotalCost: { easternEurope: { min: 7000, max: 13000 }, westernEurope: { min: 18000, max: 27000 } },
  },
  {
    courseId: 'economics_bsc',
    degreeLevel: 'BSc',
    subject: 'Economics',
    tuitionRangeEUR: { min: 1500, max: 7000 },
    typicalLanguage: 'English',
    notes: 'Strong theoretical programs in many public universities.',
    estTotalCost: { easternEurope: { min: 7000, max: 12500 }, westernEurope: { min: 17000, max: 26000 } },
  },
  {
    courseId: 'finance_bsc',
    degreeLevel: 'BSc',
    subject: 'Finance / Banking / Accounting',
    tuitionRangeEUR: { min: 2000, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Often includes preparation for professional certifications.',
    estTotalCost: { easternEurope: { min: 7500, max: 14000 }, westernEurope: { min: 19000, max: 30000 } },
  },
  {
    courseId: 'marketing_bsc',
    degreeLevel: 'BSc',
    subject: 'Marketing / Digital Marketing',
    tuitionRangeEUR: { min: 1500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Practical and project-based learning is common.',
    estTotalCost: { easternEurope: { min: 7000, max: 14500 }, westernEurope: { min: 18000, max: 30000 } },
  },
   {
    courseId: 'ir_bsc',
    degreeLevel: 'BSc',
    subject: 'International Relations / Political Science',
    tuitionRangeEUR: { min: 1500, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Ideal for careers in diplomacy, NGOs, and international organizations.',
    estTotalCost: { easternEurope: { min: 7000, max: 14000 }, westernEurope: { min: 18000, max: 29000 } },
  },
  // Arts, Design & Humanities BSc
  {
    courseId: 'architecture_bsc',
    degreeLevel: 'BSc',
    subject: 'Architecture',
    tuitionRangeEUR: { min: 2500, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Studio fees may be extra. Portfolio required for admission.',
    estTotalCost: { easternEurope: { min: 8500, max: 18000 }, westernEurope: { min: 20000, max: 35000 } },
  },
  {
    courseId: 'design_bsc',
    degreeLevel: 'BSc',
    subject: 'Design / Industrial Design',
    tuitionRangeEUR: { min: 2000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Portfolio is key. Look for programs with good industry connections.',
    estTotalCost: { easternEurope: { min: 8000, max: 16000 }, westernEurope: { min: 19000, max: 32000 } },
  },
  {
    courseId: 'fine_arts_bsc',
    degreeLevel: 'BSc',
    subject: 'Fine Arts / Visual Arts',
    tuitionRangeEUR: { min: 1500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Focus on portfolio development and creative expression.',
    estTotalCost: { easternEurope: { min: 7500, max: 15000 }, westernEurope: { min: 18000, max: 30000 } },
  },
  {
    courseId: 'media_bsc',
    degreeLevel: 'BSc',
    subject: 'Media & Communications',
    tuitionRangeEUR: { min: 1500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Includes journalism, film studies, and digital media production.',
    estTotalCost: { easternEurope: { min: 7500, max: 15000 }, westernEurope: { min: 18000, max: 30000 } },
  },
   {
    courseId: 'languages_bsc',
    degreeLevel: 'BSc',
    subject: 'Languages & Literature / Translation',
    tuitionRangeEUR: { min: 1200, max: 7500 },
    typicalLanguage: 'English',
    notes: 'Very affordable way to gain fluency and cultural expertise.',
    estTotalCost: { easternEurope: { min: 6500, max: 13000 }, westernEurope: { min: 16000, max: 27000 } },
  },
  // Professional & Emerging BSc
  {
    courseId: 'law_bsc',
    degreeLevel: 'BSc',
    subject: 'Law (LLB / LLM)',
    tuitionRangeEUR: { min: 3000, max: 12000 },
    typicalLanguage: 'English',
    notes: 'International and EU law are common English tracks. Local practice requires local bar exam.',
    estTotalCost: { easternEurope: { min: 9000, max: 18000 }, westernEurope: { min: 20000, max: 35000 } },
  },
  {
    courseId: 'education_bsc',
    degreeLevel: 'BSc',
    subject: 'Education / Teaching',
    tuitionRangeEUR: { min: 1500, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Focus on international education systems and pedagogy.',
    estTotalCost: { easternEurope: { min: 7000, max: 14000 }, westernEurope: { min: 18000, max: 29000 } },
  },
   {
    courseId: 'logistics_bsc',
    degreeLevel: 'BSc',
    subject: 'Supply Chain / Logistics',
    tuitionRangeEUR: { min: 2000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Strong programs in countries with major ports and trade hubs like Netherlands, Poland.',
    estTotalCost: { easternEurope: { min: 7500, max: 16000 }, westernEurope: { min: 19000, max: 32000 } },
  },
  {
    courseId: 'hospitality_bsc',
    degreeLevel: 'BSc',
    subject: 'Hospitality & Tourism Management',
    tuitionRangeEUR: { min: 2000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Internship-heavy programs are common.',
    estTotalCost: { easternEurope: { min: 7500, max: 16000 }, westernEurope: { min: 19000, max: 32000 } },
  },
  {
    courseId: 'sports_sci_bsc',
    degreeLevel: 'BSc',
    subject: 'Sports Science / Performance',
    tuitionRangeEUR: { min: 1500, max: 8000 },
    typicalLanguage: 'English',
    notes: 'Covers biomechanics, nutrition, and coaching.',
    estTotalCost: { easternEurope: { min: 7000, max: 13500 }, westernEurope: { min: 18000, max: 28000 } },
  },
  {
    courseId: 'agri_sci_bsc',
    degreeLevel: 'BSc',
    subject: 'Agricultural Sciences / Food Tech',
    tuitionRangeEUR: { min: 1500, max: 8000 },
    typicalLanguage: 'English',
    notes: 'Strong programs in countries with large agricultural sectors like Poland, Hungary.',
    estTotalCost: { easternEurope: { min: 7000, max: 13500 }, westernEurope: { min: 18000, max: 28000 } },
  },
  {
    courseId: 'culinary_bsc',
    degreeLevel: 'BSc',
    subject: 'Culinary Arts / Chef Programs',
    tuitionRangeEUR: { min: 2000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Vocational focus with lots of practical training.',
    estTotalCost: { easternEurope: { min: 8000, max: 16000 }, westernEurope: { min: 20000, max: 32000 } },
  },
   {
    courseId: 'aviation_bsc',
    degreeLevel: 'BSc',
    subject: 'Aviation / Pilot Training',
    tuitionRangeEUR: { min: 10000, max: 30000 },
    typicalLanguage: 'English',
    notes: 'Special case: high cost due to flight hours. Often exceeds affordable range.',
    estTotalCost: { easternEurope: { min: 20000, max: 40000 }, westernEurope: { min: 30000, max: 60000 } },
  },
  // MSc Programs Start Here
  // ENGINEERING & TECHNOLOGY MSc
  {
    courseId: 'aero_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Aerospace / Aeronautical Engineering',
    tuitionRangeEUR: { min: 3000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Focus on propulsion, avionics, flight dynamics, design optimization.',
    estTotalCost: { easternEurope: { min: 9000, max: 16000 }, westernEurope: { min: 20000, max: 33000 } },
  },
  {
    courseId: 'mech_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Mechanical Engineering',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'CAD, thermal systems, robotics integration.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 31000 } },
  },
  {
    courseId: 'civil_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Civil Engineering',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Advanced infrastructure, geotechnics, sustainability.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 31000 } },
  },
  {
    courseId: 'elec_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Electrical / Electronic Engineering',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Embedded systems, microelectronics, signal processing.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  {
    courseId: 'mecha_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Mechatronics / Robotics',
    tuitionRangeEUR: { min: 3000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Automation, control, intelligent systems.',
    estTotalCost: { easternEurope: { min: 9000, max: 16000 }, westernEurope: { min: 20000, max: 33000 } },
  },
  {
    courseId: 'chem_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Chemical Engineering',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Sustainable processes, materials science, reaction engineering.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  {
    courseId: 'biomed_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Biomedical Engineering',
    tuitionRangeEUR: { min: 3500, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Biomechanics, medical devices, bioinformatics.',
    estTotalCost: { easternEurope: { min: 9500, max: 16000 }, westernEurope: { min: 21000, max: 34000 } },
  },
  {
    courseId: 'energy_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Petroleum / Energy Engineering',
    tuitionRangeEUR: { min: 3500, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Drilling, energy management, renewables transition.',
    estTotalCost: { easternEurope: { min: 9500, max: 18000 }, westernEurope: { min: 22000, max: 36000 } },
  },
  {
    courseId: 'env_eng_msc',
    degreeLevel: 'MSc',
    subject: 'Environmental Engineering',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Climate systems, waste management, green tech.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  // COMPUTER & DATA SCIENCES MSc
  {
    courseId: 'cs_se_msc',
    degreeLevel: 'MSc',
    subject: 'Computer Science / Software Engineering',
    tuitionRangeEUR: { min: 3000, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Advanced programming, AI, systems design.',
    estTotalCost: { easternEurope: { min: 9000, max: 18000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  {
    courseId: 'ds_ai_msc',
    degreeLevel: 'MSc',
    subject: 'Data Science / Artificial Intelligence',
    tuitionRangeEUR: { min: 4000, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Deep learning, big data analytics, automation.',
    estTotalCost: { easternEurope: { min: 10000, max: 18000 }, westernEurope: { min: 23000, max: 36000 } },
  },
  {
    courseId: 'cyber_sec_msc',
    degreeLevel: 'MSc',
    subject: 'Cybersecurity / Network Management',
    tuitionRangeEUR: { min: 3000, max: 11000 },
    typicalLanguage: 'English',
    notes: 'Ethical hacking, digital forensics, secure systems.',
    estTotalCost: { easternEurope: { min: 9000, max: 17000 }, westernEurope: { min: 21000, max: 34000 } },
  },
  {
    courseId: 'iot_sys_msc',
    degreeLevel: 'MSc',
    subject: 'Cyber Physical Systems / IoT',
    tuitionRangeEUR: { min: 3000, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Smart systems, sensors, AI integration.',
    estTotalCost: { easternEurope: { min: 9000, max: 15500 }, westernEurope: { min: 20000, max: 32500 } },
  },
  // SCIENCE & RESEARCH MSc
  {
    courseId: 'physics_msc',
    degreeLevel: 'MSc',
    subject: 'Physics',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Quantum mechanics, optics, materials research.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 31000 } },
  },
  {
    courseId: 'chemistry_msc',
    degreeLevel: 'MSc',
    subject: 'Chemistry',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Lab synthesis, nanomaterials, chemical process design.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 31000 } },
  },
  {
    courseId: 'biology_msc',
    degreeLevel: 'MSc',
    subject: 'Biology / Life Sciences',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Biotechnology, genomics, microbiology.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  {
    courseId: 'math_msc',
    degreeLevel: 'MSc',
    subject: 'Mathematics / Applied Mathematics',
    tuitionRangeEUR: { min: 2000, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Modeling, stochastic processes, computational analysis.',
    estTotalCost: { easternEurope: { min: 8000, max: 14500 }, westernEurope: { min: 18000, max: 30500 } },
  },
  {
    courseId: 'stats_msc',
    degreeLevel: 'MSc',
    subject: 'Statistics',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Often linked with data science or economics departments.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  {
    courseId: 'geography_msc',
    degreeLevel: 'MSc',
    subject: 'Geography / Geosciences',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Geophysics, environmental change, GIS systems.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 31000 } },
  },
  // MEDICAL & HEALTH SCIENCES MSc
  {
    courseId: 'medicine_md_msc',
    degreeLevel: 'MSc',
    subject: 'Medicine (MD / integrated programmes)',
    tuitionRangeEUR: { min: 8000, max: 15000 },
    typicalLanguage: 'English + Local',
    notes: 'Pre-clinical + clinical rotations, research-based curriculum.',
    estTotalCost: { easternEurope: { min: 17000, max: 26000 }, westernEurope: { min: 28000, max: 40000 } },
  },
  {
    courseId: 'dentistry_msc',
    degreeLevel: 'MSc',
    subject: 'Dentistry / Dental Medicine',
    tuitionRangeEUR: { min: 6000, max: 15000 },
    typicalLanguage: 'English + Local',
    notes: 'Advanced oral medicine, prosthodontics, surgery.',
    estTotalCost: { easternEurope: { min: 15000, max: 25000 }, westernEurope: { min: 26000, max: 40000 } },
  },
  {
    courseId: 'pharmacy_msc',
    degreeLevel: 'MSc',
    subject: 'Pharmacy',
    tuitionRangeEUR: { min: 3500, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Drug design, regulatory sciences.',
    estTotalCost: { easternEurope: { min: 9500, max: 18000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  {
    courseId: 'public_health_msc',
    degreeLevel: 'MSc',
    subject: 'Public Health',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Epidemiology, health policy, data for health.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  {
    courseId: 'biomed_sci_msc',
    degreeLevel: 'MSc',
    subject: 'Biomedical Science / Laboratory Science',
    tuitionRangeEUR: { min: 3000, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Diagnostics, biochemistry, lab tech.',
    estTotalCost: { easternEurope: { min: 9000, max: 15500 }, westernEurope: { min: 20000, max: 32000 } },
  },
  {
    courseId: 'physio_msc',
    degreeLevel: 'MSc',
    subject: 'Physiotherapy / Occupational Therapy',
    tuitionRangeEUR: { min: 3000, max: 10000 },
    typicalLanguage: 'English + Local',
    notes: 'Neuromuscular therapy, rehabilitation.',
    estTotalCost: { easternEurope: { min: 9000, max: 16000 }, westernEurope: { min: 20000, max: 33000 } },
  },
  {
    courseId: 'nursing_msc',
    degreeLevel: 'MSc',
    subject: 'Nursing (BSc / MSc)',
    tuitionRangeEUR: { min: 2500, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Clinical leadership, advanced practice nursing.',
    estTotalCost: { easternEurope: { min: 8500, max: 14500 }, westernEurope: { min: 19500, max: 30500 } },
  },
  {
    courseId: 'med_biotech_msc',
    degreeLevel: 'MSc',
    subject: 'Medical Biotechnology',
    tuitionRangeEUR: { min: 3000, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Advanced degree focusing on technology in medicine.',
    estTotalCost: { easternEurope: { min: 9500, max: 18000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  // BUSINESS & ECONOMICS MSc
  {
    courseId: 'business_msc',
    degreeLevel: 'MSc',
    subject: 'Business Administration / Management',
    tuitionRangeEUR: { min: 2500, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Strategy, management, operations.',
    estTotalCost: { easternEurope: { min: 8500, max: 16000 }, westernEurope: { min: 19500, max: 33000 } },
  },
  {
    courseId: 'finance_msc',
    degreeLevel: 'MSc',
    subject: 'Finance / Banking / Accounting',
    tuitionRangeEUR: { min: 3000, max: 12000 },
    typicalLanguage: 'English',
    notes: 'Quantitative finance, auditing, corporate valuation.',
    estTotalCost: { easternEurope: { min: 9000, max: 18000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  {
    courseId: 'marketing_msc',
    degreeLevel: 'MSc',
    subject: 'Marketing / Digital Marketing',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Branding, SEO, data-driven marketing.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19500, max: 31000 } },
  },
  {
    courseId: 'economics_msc',
    degreeLevel: 'MSc',
    subject: 'Economics',
    tuitionRangeEUR: { min: 2000, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Policy analysis, applied data.',
    estTotalCost: { easternEurope: { min: 8000, max: 15000 }, westernEurope: { min: 18000, max: 31000 } },
  },
  {
    courseId: 'logistics_msc',
    degreeLevel: 'MSc',
    subject: 'Supply Chain / Logistics',
    tuitionRangeEUR: { min: 3000, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Procurement, operations, global logistics.',
    estTotalCost: { easternEurope: { min: 9000, max: 15000 }, westernEurope: { min: 20000, max: 31000 } },
  },
  {
    courseId: 'hospitality_msc',
    degreeLevel: 'MSc',
    subject: 'Hospitality & Tourism Management',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Service design, destination marketing.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  // LAW, SOCIAL & HUMANITIES MSc
  {
    courseId: 'law_msc',
    degreeLevel: 'MSc',
    subject: 'Law (LLB / LLM)',
    tuitionRangeEUR: { min: 3000, max: 12000 },
    typicalLanguage: 'English',
    notes: 'International law, human rights, arbitration.',
    estTotalCost: { easternEurope: { min: 9000, max: 18000 }, westernEurope: { min: 22000, max: 35000 } },
  },
  {
    courseId: 'ir_msc',
    degreeLevel: 'MSc',
    subject: 'International Relations / Political Science',
    tuitionRangeEUR: { min: 2000, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Diplomacy, governance, policy design.',
    estTotalCost: { easternEurope: { min: 8000, max: 15000 }, westernEurope: { min: 18000, max: 31000 } },
  },
  {
    courseId: 'psychology_msc',
    degreeLevel: 'MSc',
    subject: 'Psychology',
    tuitionRangeEUR: { min: 3000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Behavioral science, cognitive research.',
    estTotalCost: { easternEurope: { min: 9000, max: 16000 }, westernEurope: { min: 20000, max: 33000 } },
  },
  // ARTS, DESIGN & CULTURE MSc
  {
    courseId: 'fine_arts_msc',
    degreeLevel: 'MSc',
    subject: 'Fine Arts / Visual Arts',
    tuitionRangeEUR: { min: 2000, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Painting, multimedia, creative arts.',
    estTotalCost: { easternEurope: { min: 8000, max: 15000 }, westernEurope: { min: 18000, max: 31000 } },
  },
  {
    courseId: 'media_msc',
    degreeLevel: 'MSc',
    subject: 'Media & Communications',
    tuitionRangeEUR: { min: 2500, max: 9500 },
    typicalLanguage: 'English',
    notes: 'Media strategy, PR, content creation.',
    estTotalCost: { easternEurope: { min: 8500, max: 15500 }, westernEurope: { min: 19500, max: 32000 } },
  },
  {
    courseId: 'languages_msc',
    degreeLevel: 'MSc',
    subject: 'Languages & Literature / Translation',
    tuitionRangeEUR: { min: 1500, max: 7000 },
    typicalLanguage: 'English',
    notes: 'Linguistics, comparative literature.',
    estTotalCost: { easternEurope: { min: 7500, max: 13000 }, westernEurope: { min: 17500, max: 29000 } },
  },
  {
    courseId: 'african_studies_msc',
    degreeLevel: 'MSc',
    subject: 'African Studies / Area Studies',
    tuitionRangeEUR: { min: 2000, max: 8000 },
    typicalLanguage: 'English',
    notes: 'History, culture, policy.',
    estTotalCost: { easternEurope: { min: 8000, max: 14000 }, westernEurope: { min: 18000, max: 30000 } },
  },
  {
    courseId: 'education_msc',
    degreeLevel: 'MSc',
    subject: 'Education / Teaching',
    tuitionRangeEUR: { min: 2000, max: 8500 },
    typicalLanguage: 'English',
    notes: 'Pedagogy, education leadership.',
    estTotalCost: { easternEurope: { min: 8000, max: 14500 }, westernEurope: { min: 18000, max: 30500 } },
  },
  // EMERGING FIELDS MSc
  {
    courseId: 'renewable_energy_msc',
    degreeLevel: 'MSc',
    subject: 'Renewable Energy / Sustainable Tech',
    tuitionRangeEUR: { min: 3000, max: 10000 },
    typicalLanguage: 'English',
    notes: 'Energy policy, green systems.',
    estTotalCost: { easternEurope: { min: 9000, max: 16000 }, westernEurope: { min: 20000, max: 33000 } },
  },
  {
    courseId: 'urban_planning_msc',
    degreeLevel: 'MSc',
    subject: 'Urban Planning / Smart Cities',
    tuitionRangeEUR: { min: 2500, max: 9000 },
    typicalLanguage: 'English',
    notes: 'Mobility, spatial planning.',
    estTotalCost: { easternEurope: { min: 8500, max: 15000 }, westernEurope: { min: 19000, max: 31000 } },
  },
];


const iconMap: Record<string, LucideIcon> = {
  // STEM & Engineering
  "Aerospace / Aeronautical Engineering": Plane,
  "Mechanical Engineering": Cog,
  "Civil Engineering": Landmark,
  "Electrical / Electronic Engineering": Cpu,
  "Mechatronics / Robotics": Bot,
  "Chemical Engineering": Beaker,
  "Biomedical Engineering": Dna,
  "Petroleum / Energy Engineering": Factory,
  "Environmental Engineering": Leaf,
  // Computer Science & Data
  "Computer Science / Software Engineering": Code,
  "Data Science / Artificial Intelligence": LineChart,
  "Cybersecurity / Network Management": ShieldCheck,
  "Cyber Physical Systems / IoT": Anchor,
  // Math & Natural Sciences
  "Mathematics / Applied Mathematics": Sigma,
  "Physics": Atom,
  "Chemistry": TestTube,
  "Biology / Life Sciences": Dna,
  "Geography / Geosciences": Globe,
  "Statistics": TrendingUp,
  // Health & Medical
  "Medicine (MD / integrated programmes)": HeartPulse,
  "Dentistry / Dental Medicine": HeartPulse, // No 'Tooth' icon, using generic health
  "Pharmacy": Beaker,
  "Nursing (BSc / MSc)": HeartPulse,
  "Public Health": HeartPulse,
  "Biomedical Science / Laboratory Science": TestTube,
  "Physiotherapy / Occupational Therapy": Dumbbell,
  "Medical Biotechnology": Dna,
  // Business, Economics & Social Sciences
  "Business Administration / Management": Briefcase,
  "Economics": TrendingDown,
  "Finance / Banking / Accounting": LineChart,
  "Marketing / Digital Marketing": Mic,
  "International Relations / Political Science": Book,
  "Psychology": Book,
  "Sociology / Social Work": Book,
  "Human Resources": Briefcase,
  // Arts, Design & Humanities
  "Architecture": Building2,
  "Design / Industrial Design": Brush,
  "Fine Arts / Visual Arts": Brush,
  "Media & Communications": Mic,
  "Languages & Literature / Translation": BookOpen,
  "African Studies / Area Studies": BookOpen,
  // Professional & Emerging Fields
  "Law (LLB / LLM)": Scale,
  "Education / Teaching": GraduationCap,
  "Supply Chain / Logistics": Ship,
  "Hospitality & Tourism Management": Hotel,
  "Sports Science / Performance": Dumbbell,
  "Renewable Energy / Sustainable Tech": Leaf,
  "Urban Planning / Smart Cities": Landmark,
  "Agricultural Sciences / Food Tech": Leaf,
  "Culinary Arts / Chef Programs": Soup,
  "Aviation / Pilot Training": Plane,
};

export const getProgramIcon = (subject: string): LucideIcon => {
  return iconMap[subject] || BookOpen; // Default icon
};
