
import type { University } from './types';

// This file is being replaced by featured-universities.json
// It is kept for now to prevent breaking existing components, but should be deprecated.

export const universityData: University[] = [
  {
    id: 'charles-university',
    name: 'Charles University',
    country: 'Czech Republic',
    countryCode: 'CZ',
    annualCost: 6000,
    highlights: ['Top Engineering & Research', 'Historic Prague campus', 'Strong international exchange'],
    imageId: 'university-1',
    motto: "Excellence in Research and Teaching",
    featured: true,
  },
  {
    id: 'university-of-warsaw',
    name: 'University of Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    annualCost: 4500,
    highlights: ['Arts & Humanities', 'Historic campus', 'Central European hub'],
    imageId: 'university-2',
    motto: "Creators of futures since 1816",
    featured: false,
  },
    {
    id: 'vilnius-university',
    name: 'Vilnius University',
    country: 'Lithuania',
    countryCode: 'LT',
    annualCost: 3500,
    highlights: ['Oldest in Baltics', 'Physics & Life Sciences', 'UNESCO Heritage Campus'],
    imageId: 'university-3',
    motto: "Hinc itur ad astra",
    featured: false,
  },
  {
    id: 'university-of-porto',
    name: 'University of Porto',
    country: 'Portugal',
    countryCode: 'PT',
    annualCost: 1500,
    highlights: ['Strong Engineering', 'Life Sciences', 'Coastal City Campus'],
    imageId: 'university-4',
    motto: "Virtus Unita Fortius Agit",
    featured: false,
  },
  {
    id: 'university-of-tartu',
    name: 'University of Tartu',
    country: 'Estonia',
    countryCode: 'EE',
    annualCost: 5000,
    highlights: ['Top Baltic Research', 'Modern STEM', 'Social Programmes'],
    imageId: 'university-5',
    motto: "A University of the Mind",
    featured: false,
  },
  {
    id: 'university-of-belgrade',
    name: 'University of Belgrade',
    country: 'Serbia',
    countryCode: 'RS',
    annualCost: 3000,
    highlights: ['Low International Tuition', 'Engineering & Humanities', 'Large Public University'],
    imageId: 'university-6',
    motto: "For the freedom of the mind",
    featured: false,
  },
  {
    id: 'national-taiwan-university',
    name: 'National Taiwan University',
    country: 'Taiwan',
    countryCode: 'TW',
    annualCost: 4500,
    highlights: ['Top in Taiwan', 'Strong Engineering', 'Computer Science Research'],
    imageId: 'university-7',
    motto: "Integrity, Diligence, Fidelity, and Compassion",
    featured: true,
  },
  {
    id: 'universiti-malaya',
    name: 'Universiti Malaya',
    country: 'Malaysia',
    countryCode: 'MY',
    annualCost: 4000,
    highlights: ["Malaysia's Top University", 'Affordable English Programs', 'Strong Engineering'],
    imageId: 'university-8',
    motto: "Ilmu Puncha Kemajuan",
    featured: false,
  },
  {
    id: 'university-of-ghana',
    name: 'University of Ghana',
    country: 'Ghana',
    countryCode: 'GH',
    annualCost: 4000,
    highlights: ['Top in West Africa', 'Business & Social Sciences', 'Health Programs'],
    imageId: 'university-9',
    motto: "Integri Procedamus",
    featured: false,
  },
  {
    id: 'makerere-university',
    name: 'Makerere University',
    country: 'Uganda',
    countryCode: 'UG',
    annualCost: 2000,
    highlights: ["East Africa's Oldest", 'Large Research University', 'Broad Program Portfolio'],
    imageId: 'university-10',
    motto: "We Build for the Future",
    featured: false,
  },
  {
    id: 'university-of-buenos-aires',
    name: 'University of Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    annualCost: 500,
    highlights: ['Tuition-Free Undergraduate', 'Top in Latin America', 'Strong Humanities'],
    imageId: 'university-11',
    motto: "Argentina Virtus Robur et Studium",
    featured: true,
  },
  {
    id: 'university-of-sao-paulo',
    name: 'University of São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    annualCost: 500,
    highlights: ["Brazil's Premier Public University", 'Tuition-Free Programs', 'Top Research'],
    imageId: 'university-12',
    motto: "Scientia Vinces",
    featured: false,
  }
];
