
import type { University } from './types';

export const universityData: University[] = [
  {
    id: '1',
    name: 'Charles University',
    country: 'Czech Republic',
    countryCode: 'CZ',
    annualCost: 6000,
    highlights: ['Top Engineering Program', 'Research Focused', 'Vibrant Student Life'],
    imageId: 'university-1',
    motto: "Excellence in Research and Teaching",
  },
  {
    id: '2',
    name: 'University of Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    annualCost: 4500,
    highlights: ['Arts & Humanities', 'Historic Campus', 'Located in Warsaw'],
    imageId: 'university-2',
    motto: "Creators of futures since 1816",
  },
  {
    id: '3',
    name: 'Vilnius University',
    country: 'Lithuania',
    countryCode: 'LT',
    annualCost: 3500,
    highlights: ['Oldest in Baltics', 'Physics & Life Sciences', 'UNESCO Heritage Campus'],
    imageId: 'university-3',
    motto: "Hinc itur ad astra",
  },
  {
    id: '4',
    name: 'University of Porto',
    country: 'Portugal',
    countryCode: 'PT',
    annualCost: 1500,
    highlights: ['Strong Engineering', 'Life Sciences', 'Coastal City Campus'],
    imageId: 'university-4',
    motto: "Virtus Unita Fortius Agit",
  },
  {
    id: '5',
    name: 'University of Tartu',
    country: 'Estonia',
    countryCode: 'EE',
    annualCost: 5000,
    highlights: ['Top Baltic Research', 'Modern STEM', 'Social Programmes'],
    imageId: 'university-5',
    motto: "A University of the Mind",
  },
  {
    id: '6',
    name: 'University of Belgrade',
    country: 'Serbia',
    countryCode: 'RS',
    annualCost: 3000,
    highlights: ['Low International Tuition', 'Engineering & Humanities', 'Large Public University'],
    imageId: 'university-6',
    motto: "For the freedom of the mind",
  },
  {
    id: '7',
    name: 'National Taiwan University',
    country: 'Taiwan',
    countryCode: 'TW',
    annualCost: 4500,
    highlights: ['Top in Taiwan', 'Strong Engineering', 'Computer Science Research'],
    imageId: 'university-7',
    motto: "Integrity, Diligence, Fidelity, and Compassion",
  },
  {
    id: '8',
    name: 'Universiti Malaya',
    country: 'Malaysia',
    countryCode: 'MY',
    annualCost: 4000,
    highlights: ["Malaysia's Top University", 'Affordable English Programs', 'Strong Engineering'],
    imageId: 'university-8',
    motto: "Ilmu Puncha Kemajuan",
  },
  {
    id: '9',
    name: 'University of Ghana',
    country: 'Ghana',
    countryCode: 'GH',
    annualCost: 4000,
    highlights: ['Top in West Africa', 'Business & Social Sciences', 'Health Programs'],
    imageId: 'university-9',
    motto: "Integri Procedamus",
  },
  {
    id: '10',
    name: 'Makerere University',
    country: 'Uganda',
    countryCode: 'UG',
    annualCost: 2000,
    highlights: ["East Africa's Oldest", 'Large Research University', 'Broad Program Portfolio'],
    imageId: 'university-10',
    motto: "We Build for the Future",
  },
  {
    id: '11',
    name: 'University of Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    annualCost: 500,
    highlights: ['Tuition-Free Undergraduate', 'Top in Latin America', 'Strong Humanities'],
    imageId: 'university-11',
    motto: "Argentina Virtus Robur et Studium",
  },
  {
    id: '12',
    name: 'University of São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    annualCost: 500,
    highlights: ["Brazil's Premier Public University", 'Tuition-Free Programs', 'Top Research'],
    imageId: 'university-12',
    motto: "Scientia Vinces",
  },
];
