import type { University } from './types';

export const universityData: University[] = [
  {
    id: '1',
    name: 'Charles University',
    country: 'Czech Republic',
    countryCode: 'CZ',
    annualCost: 6000,
    highlights: ['Top Engineering Program', 'Research Focused', 'Vibrant Student Life'],
    imageId: 'university-1',
    motto: "Excellence in Research and Teaching",
  },
  {
    id: '2',
    name: 'University of Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    annualCost: 4500,
    highlights: ['Arts & Humanities', 'Historic Campus', 'Located in Warsaw'],
    imageId: 'university-2',
    motto: "Creators of futures since 1257",
  },
  {
    id: '3',
    name: 'University of Vienna',
    country: 'Austria',
    countryCode: 'AT',
    annualCost: 1500,
    highlights: ['Diverse Programs', 'Historical Significance', 'Major research university'],
    imageId: 'university-3',
    motto: "Alma Mater Rudolphina Vindobonensis",
  },
  {
    id: '4',
    name: 'Jagiellonian University',
    country: 'Poland',
    countryCode: 'PL',
    annualCost: 4000,
    highlights: ['Medicine', 'International Relations', 'Historic University'],
    imageId: 'university-4',
    motto: "Plus ratio quam vis",
  },
  {
    id: '5',
    name: 'University of Debrecen',
    country: 'Hungary',
    countryCode: 'HU',
    annualCost: 5500,
    highlights: ['Medical Programs', 'Large International Community', 'Affordable Living'],
    imageId: 'university-5',
    motto: "The university is our passion",
  },
  {
    id: '6',
    name: 'Vilnius University',
    country: 'Lithuania',
    countryCode: 'LT',
    annualCost: 3500,
    highlights: ['Oldest in Baltics', 'Physics & Life Sciences', 'UNESCO Heritage Campus'],
    imageId: 'university-6',
    motto: "Hinc itur ad astra",
  },
  {
    id: '7',
    name: 'Brno University of Technology',
    country: 'Czech Republic',
    countryCode: 'CZ',
    annualCost: 4000,
    highlights: ['Strong in IT', 'Engineering', 'Vibrant Tech Scene'],
    imageId: 'university-7',
    motto: "The future is in technology",
  },
  {
    id: '8',
    name: 'Kaunas University of Technology',
    country: 'Lithuania',
    countryCode: 'LT',
    annualCost: 3000,
    highlights: ['Technology Research', 'Business & Tech', 'Startup Hub'],
    imageId: 'university-8',
    motto: "Leading to the future",
  },
  {
    id: '9',
    name: 'University of Ljubljana',
    country: 'Slovenia',
    countryCode: 'SI',
    annualCost: 5000,
    highlights: ['Comprehensive University', 'Natural Sciences', 'Mediterranean Feel'],
    imageId: 'university-9',
    motto: "In the heart of Europe, with a tradition",
  },
  {
    id: '10',
    name: 'Eötvös Loránd University (ELTE)',
    country: 'Hungary',
    countryCode: 'HU',
    annualCost: 3000,
    highlights: ['Humanities', 'Social Sciences', 'Research University'],
    imageId: 'university-10',
    motto: "Tradition and innovation",
  },
  {
    id: '11',
    name: 'University of Bucharest',
    country: 'Romania',
    countryCode: 'RO',
    annualCost: 2000,
    highlights: ['Foreign Languages', 'Affordable', 'Dynamic Capital City'],
    imageId: 'university-11',
    motto: "Virtute et sapientia",
  },
  {
    id: '12',
    name: 'University of Padua',
    country: 'Italy',
    countryCode: 'IT',
    annualCost: 2800,
    highlights: ['Founded in 1222', 'Medicine & Psychology', 'Galileo Taught Here'],
    imageId: 'university-12',
    motto: "Universa universis patavina libertas",
  },
  {
    id: '13',
    name: 'University of Pisa',
    country: 'Italy',
    countryCode: 'IT',
    annualCost: 2400,
    highlights: ['Computer Science', 'Engineering', 'Historic City'],
    imageId: 'university-13',
    motto: "In supremæ dignitatis",
  },
  {
    id: '14',
    name: 'Technical University of Ostrava',
    country: 'Czech Republic',
    countryCode: 'CZ',
    annualCost: 2500,
    highlights: ['Mining & Geology', 'Metallurgy', 'Practical Engineering'],
    imageId: 'university-14',
    motto: "Science - Technology - Education",
  },
  {
    id: '15',
    name: 'Sofia University St. Kliment Ohridski',
    country: 'Bulgaria',
    countryCode: 'BG',
    annualCost: 3300,
    highlights: ['Classical Studies', 'Law', 'Most Prestigious in Bulgaria'],
    imageId: 'university-15',
    motto: "It is the light that enlightens",
  }
];

    